name: esp32_ble_flutter
description: Flutter BLE Client for ESP32
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.0
  mobile_scanner: ^5.2.3
  permission_handler: ^11.0.1
  dio: ^5.7.0
  shared_preferences: ^2.2.2
  wifi_scan: ^0.4.1
  google_generative_ai: ^0.4.6
  intl: ^0.19.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  web_socket_channel: ^2.4.0
  flutter_map: ^6.1.0 # Hiển thị bản đồ OSM
  latlong2: ^0.9.0 # Xử lý tọa độ
  geolocator: ^11.0.0 # Lấy vị trí GPS hiện tại
flutter:
  uses-material-design: true
  assets:
    # - assets/images/onb1.jpg
    # - assets/images/onb2.jpg
    # - assets/images/onb3.jpg
    # - assets/images/onb4.jpg
    # - assets/icons/wifi.jpg
    # - assets/icons/google.jpg
    - assets/icons/iot_devices.jpg
    - assets/images/
    - assets/icons/
